/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GroupDialog: typeof import('./src/components/group-dialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
  }
}
